### PR TITLE
Country/base_set for datasets and new param to set time curves to zero on export

### LINKED ISSUE #197: Improve rake etsource:export task
After running the rake etsource:export script, a few manual steps still have to be performed for local datasets:
- The time curves have to be set to zero (discussed in https://github.com/quintel/etlocal/issues/179).
- The curves should be symlinked to `nl2016` or `nl2017` instead of `nl`, based on the analysis year. Currently, the rake export task hard-codes that each ETLocal region is in `nl` (https://github.com/quintel/etlocal/blob/master/app/models/dataset.rb#L35-L40), and so it inherits settings (and curves) from the `nl` dataset.
- More ... ?

Would it be an idea to rewrite the `etsource:export` script so that these steps are automatically performed by running the task?

### PR DESCRIPTION
**Pull request by noracato**
Closes #197 

Test after bumping Atlas (quintel/atlas#137) and Transformer (quintel/transformer#6)

- New column Country for datasets (instead of the country being frozen) allows to set the base_dataset for export
- New parameter `time_curves_to_zero` allows for all time curves to bet set to zeroes instead of being scaled

### CODE REVIEW

**Comment by noracato** [comment]
Build fails due to descrepancies between inputs in ETLocal and ETSource (due to rename of inputs in heat update?)

**Comment by redekok** [comment]
A few more questions:
- When adding the `time_curves_to_zero=true` parameter, the time curves for crude oil and natural gas are not set to zeros. Am I using this parameter incorrectly?
- After exporting a local dataset with an analysis year of 2016 or 2017, the ETSource dataset still symlinks to `nl` directories instead of `nl2016` or `nl2017` directories. Even after running the `rake symlink_nl DESTINATION=nl2016` task in ETSource. Not sure what I'm doing wrong?

> I can try to change this so a brand new version (including scaling and symlinking) will be created on every export from etlocal? Or maybe with an optional 'REBASE' flag to set on the export task? Then the symlink_curves task will become unneccesary.
- And lastly, in https://github.com/quintel/etsource/pull/2177 we've discussed the possibility above. @noracato Is this still something we'd like to implement?

**Comment by noracato** [comment]
> After exporting a local dataset with an analysis year of 2016 or 2017, the ETSource dataset still symlinks to nl directories instead of nl2016 or nl2017 directories.

Datasets in etlocal now have a new property `country` that in exporting acts as their base dataset. I chose not to use purely the analysis year to determine the base dataset, because in the future we might want to add local datasets based on eg `be` or `fr`. You can set the `country` of a dataset to any full national dataset present in etsource (in your case `nl2016`).

> When adding the time_curves_to_zero=true parameter, the time curves for crude oil and natural gas are not set to zeros. Am I using this parameter incorrectly?

Have you tried completely removing the folder from etsource first? And did you write the parameter in all caps? `TIME_CURVES_TO_ZERO=true`

> Is this still something we'd like to implement?

I'ts a bit more complicated than I thought. I think I will leave this for this PR and put it on the backlog, if that's ok with you.

**Comment by redekok** [comment]
> And did you write the parameter in all caps?

That did the trick, thanks! 🤓 

> It's a bit more complicated than I thought. I think I will leave this for this PR and put it on the backlog, if that's ok with you.

👍

**Pull request merged**
