### PR TITLE
Add hourly curves, emission factors and fuel production

### PR DESCRIPTION
**Pull request by marliekeverweij**
Comments:

- The rake task to ETSource probably has to be adjusted now that we do not have to set all time curves to zero anymore for regional datasets. Who can do that best @antw / @michieldenhaan ?
- I have only included one of the solar_pv curves (`solar_pv_profile_1`) as I find it confusing to add all
- I have not included `industry_chp` as this is a flat curve and is not used in industry chp nodes as far as I can see. Maybe we can remove this curve from all datasets and use the `flat` curve instead?
- I haven't had time to add descriptions to each individual curve. We could do that, but not sure if that's necessary at this point. What do you think @michieldenhaan ?

### CODE REVIEW

**Comment by antw** [comment]
> The rake task to ETSource probably has to be adjusted

Already taken care of.

**Review by michieldenhaan — COMMENTED** [review]
@Charlottevm @marliekeverweij What do you think about separating the emission factors into sub groups? The list is quite long now. For example: General (oil, natural gas, coal, lignite, non-biogenic waste), Transport fuels (diesel, gasoline, kerosene, LPG, LNG, HFO) and Import (imported electricity, imported heat)?

image

**Comment by marliekeverweij** [comment]
Good idea! Shall I update it or will you?

**Comment by Charlottevm** [comment]
Yes nice idea! I can also update?

**Review by michieldenhaan — APPROVED** [review]

**Pull request merged**
