### PR TITLE
Dataset Province of Noord-Holland update to 2022 

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
This PR updates the province of Noord-Holland to 2022. 
In this update we mostly took the 2019 dataset and updated the most notable changes in Klimaatmonitor. This effort is therefore useful for new studies with this dataset.

Goes together with: https://github.com/quintel/etsource/pull/3135

### CODE REVIEW

**Review by MartLubben — APPROVED** [review]

**Review by noracato — CHANGES_REQUESTED** [review]
Hey @kaskranenburgQ! I understand your wish for a more clear message and value your enthusiasm, but changes like these should come in a separate PR. Right now I don't have the time or insight to review your changes, and that is blocking the merge of the new data.

What would work best next time is to open an issue where we can discuss the actual need (maybe more messages can be clarified) and update the code in all places necessary when we address it in the sprint.

If you could remove the code in the `importable_commit` and move it to an issue, that would be great!

**Comment by kaskranenburgQ** [comment]
@noracato Alright! Will do that.

**Comment by kaskranenburgQ** [comment]
With the removal of the changes for the file importable_commit.rb the migration will no longer run.
The error message as described in #545 pops up.
When I run the migration with the changes in importable_commit, it stated that the columns 'country' and 'name' where not in the edtiable attributes of the dataset and so it skipped over these keys . One would think that leaving them out of the migration with the regular code for importable_commit.rb would then be the solution. If you do an error pops up stating that 'country' and 'name' are missing mandatory headers, so the migration does not run. Therefore I'm not sure what to do anymore. @noracato From this description, do you have an idea about what's going on.

**Comment by kaskranenburgQ** [comment]
Thanks to @louispt1 the issue is fixed! We can go ahead with the merge!

**Review by MartLubben — APPROVED** [review]

**Review by noracato — APPROVED** [review]

**Pull request merged**
