### PR TITLE
Added the efficiencies of power/heat plants in dataset manager

### LINKED ISSUE #319: Add interface elements for efficiencies of power and heat plants
It will be possible to set the present efficiencies for power and heat plants per region ✨

For this it is necessary to add these fields to ETLocal. We would like to add a new tab 'Efficiencies' to the section 'Energy production' section of the Dataset Manager.

Here is the list with power and heat plants:
energy_heat_burner_wood_pellets
energy_heat_burner_coal
energy_heat_burner_hydrogen
energy_heat_burner_crude_oil
energy_heat_burner_network_gas
energy_heat_burner_waste_mix
energy_heat_heatpump_water_water_electricity
energy_chp_local_engine_network_gas
energy_chp_local_engine_biogas
energy_chp_local_wood_pellets
energy_chp_combined_cycle_network_gas
energy_chp_ultra_supercritical_cofiring_coal
energy_chp_ultra_supercritical_coal
energy_chp_ultra_supercritical_lignite
energy_chp_supercritical_waste_mix
energy_power_supercritical_coal
energy_power_ultra_supercritical_coal
energy_power_ultra_supercritical_ccs_coal
energy_power_ultra_supercritical_cofiring_coal
energy_power_combined_cycle_coal
energy_power_combined_cycle_ccs_coal
energy_power_ultra_supercritical_lignite
energy_power_ultra_supercritical_oxyfuel_ccs_lignite
energy_power_turbine_network_gas
energy_power_combined_cycle_network_gas
energy_power_combined_cycle_ccs_network_gas
energy_power_ultra_supercritical_network_gas
energy_power_ultra_supercritical_crude_oil
energy_power_engine_diesel
energy_power_engine_network_gas
energy_power_supercritical_waste_mix
energy_power_nuclear_gen2_uranium_oxide
energy_power_nuclear_gen3_uranium_oxide
industry_chp_turbine_gas_power_fuelmix
industry_chp_engine_gas_power_fuelmix
industry_chp_combined_cycle_gas_power_fuelmix
industry_chp_ultra_supercritical_coal
industry_chp_wood_pellets
industry_heat_burner_lignite
industry_heat_burner_coal
industry_heat_burner_crude_oil

For electricity plants only the `electricity_output_conversion` have to be set
For heat plants only the `steam_hot_water_output_conversion`
For CHPs both the `steam_hot_water_output_conversion` as the `electricity_output_conversion`

### PR DESCRIPTION
**Pull request by Charlottevm**
closes  #319

### CODE REVIEW

**Review by marliekeverweij — APPROVED** [review]

**Review by michieldenhaan — CHANGES_REQUESTED** [review]
Nice work @Charlottevm, @marliekeverweij!

I have two comments:
* On my local machine the efficiencies aren't exported to the datasets' graph_values.yml. Am I doing something wrong here? This could also be the reason the ETSource spec is failing?
* For CHPs the heat efficiency translations have "(LHV)", the electricity efficiency translations do not. Is this intentional? I would prefer adding a general remark to the section's introduction, stating something like: All efficiencies assume lower heating values.

**Comment by marliekeverweij** [comment]
Thanks for looking into this, @michieldenhaan !

>On my local machine the efficiencies aren't exported to the datasets' graph_values.yml. Am I doing something wrong here? This could also be the reason the ETSource spec is failing?

Yes, I would also expect that the efficiencies would end up in the graph_values.yml. @antw, do you maybe no why the efficiencies do not end up there?

>For CHPs the heat efficiency translations have "(LHV)", the electricity efficiency translations do not. Is this intentional? I would prefer adding a general remark to the section's introduction, stating something like: All efficiencies assume lower heating values.

Good idea, I will adjust that.

**Comment by michieldenhaan** [comment]
> Yes, I would also expect that the efficiencies would end up in the graph_values.yml. @antw, do you maybe no why the efficiencies do not end up there?

I think ETLocal/Transformer doesn't know how to deal with keys ending with {carrier}_output_conversion. I guess we have two options: Add sparse graph queries per node, see e.g. https://github.com/quintel/etsource/blob/master/sparse_graph_queries/industry/industry_transformation_generic_coal%2Boutput.ad. Or adjust Transformer to set the efficiencies directly.

Minor thing: The latter would probably require that we set efficiencies as fractions in the ETLocal database, not integers as is the case in this PR.

**Comment by antw** [comment]
> @antw, do you maybe no why the efficiencies do not end up there?

It's not immediately obvious to me if this is supported today. I think it's almost certain that the attribute names are incorrect:

```
(node)_(carrier)_(direction)_conversion
```

Neither ETSource nor Atlas know of attributes called "*_conversion", as carrier shares are defined with "input" and "output" attributes. For example:

```
- input.electricity = 0.5
- input.network_gas  0.5
```

There are twenty or so nodes in ETSource which have whitelisted the "input" or "output" attributes. As far as I can tell, these values are set by "sparse graph queries" ([for example](https://github.com/quintel/etsource/blob/557a33ad94b30560543bf170cfc7430c38434419/sparse_graph_queries/transport/transport_road_mixer_lng%2Binput.ad)). I suspect this is the only way currently supported for setting these attributes.

**Pull request merged**
