### PR TITLE
Removing demands from heat pumps and assume them from the graph

### PR DESCRIPTION
**Pull request by grdw**

### CODE REVIEW

**Comment by grdw** [comment]
@BerendSmits when you have time, could you validate the outcome of the analysis. As in; does it make sense; aren't there any values which are ball-park figures off. Etc.

**Comment by grdw** [comment]
@BerendSmits I managed to reproduce #51 and fix the problem 👍

**Comment by BerendSmits** [comment]
@grdw is it true that the rake export now only works when you add a geo id in the ad file?

**Comment by BerendSmits** [comment]
The demands and shares look good, everything is what it should be :thumbsup:

**Pull request merged**
