### PR TITLE
Replace land available for solar and onshore wind by total land area attribute

### PR DESCRIPTION
**Pull request by redekok**
Fixes https://github.com/quintel/etmodel/issues/2912:
- Replace `land_available_for_solar` and `onshore_suitable_for_wind` attributes by `total_land_area` attribute in `area.yml` interface element
- Add translations for `total_land_area`
- Add migration files to set values for `total_land_area`
- Update atlas ref in Gemfile

### CODE REVIEW

**Comment by marliekeverweij** [comment]
> Do we want to remove the `land_available_for_solar` and `onshore_suitable_for_wind` attributes? Makes it harder to cherry-pick new datasets to PRO. We could also keep them for now and remove them when a deploy is scheduled

Would it be possible to hide them? For example for the workshop in Antwerp tomorrow where @MartLubben will show ETLocal, it would be nice to not discuss these two attributes

**Comment by michieldenhaan** [comment]
> Would it be possible to hide them?

We can move them to the `other` tab? :see_no_evil:

**Comment by marliekeverweij** [comment]
@redekok , 

@michieldenhaan and I thought about moving the `land_available_for_solar` and `onshore_suitable_for_wind` to "Algemeen > Geavanceerd" and then down-under with the header "Verouderde/overbodige attributen". Shall I change that?

**Comment by michieldenhaan** [comment]
Or even better, we can remove them and add two sparse graph queries to ETSource that set ``onshore_suitable_for_wind`` and ``land_available_for_solar`` based on the total area attribute in ETLocal

**Comment by redekok** [comment]
I've updated the migration files based on @michieldenhaan's comment on the ETSource PR (https://github.com/quintel/etsource/pull/2003#pullrequestreview-229575172). Are we ready to merge this PR now?

**Pull request merged**
