### PR TITLE
Add migrate files for Stedin neighbourhoods

### PR DESCRIPTION
**Pull request by redekok**
Last Friday the import of the datasets succeeded. However, git wasn't working along so I hope these are the correct files. It seems to be the case though (since there are no blank lines at the bottom of the csv anymore).

### CODE REVIEW

**Comment by redekok** [comment]
@michieldenhaan When I run ETLocal locally, the neighbourhood datasets seem to open correctly in the new neighbourhood layer. :)

**Comment by antw** [comment]
> @antw This migration took about 2 hours on my laptop to complete, is it safe to merge/auto-deploy this or is it better to do this manually?

I should probably do it manually, as the auto-deploys time-out after an hour.

> where he needs ETLocal so in any case it's better to merge this tomorrow morning.

I guess this time has passed; is is okay to deploy it now?

**Comment by michieldenhaan** [comment]
> I guess this time has passed; is is okay to deploy it now?

Yes!

**Comment by antw** [comment]
This has been deployed, and the new datasets are present in the database.

**Pull request merged**
