### PR TITLE
Add new CSV importer

### LINKED ISSUE #128: Reduce number of commit messages when updating datasets
Currently, when updating values in ETLocal each value gets its own, often redundant, commit message. This leads to a lot of database entries.

The current dataset generation process is as follows:
To generate datasets, we use data from various sources. This data is put into one excel file and subsequently combined and transformed. Ultimately, the excel file generates a csv output file in which (transformed) data is mapped to ETLocal input fields for each region:
post1

For each column in this csv, the source of the data in that row is typically the same (e.g. the source for ``input_households_electricity_demand`` is typically the same for all regions in the csv). In addition, various columns have the same source (e.g. the data for input fields 1 till 3 may come from the same source). I expect that when generating a bunch of datasets, around 20-30 unique commit messages can cover 99% of all updated values.

To reduce the number of commit messages, we can group multiple input field updates into one commit, like so:
post2

I.e. commit message 1 is applied to input fields 1 till 3, commit message 2 is applied to input fields 4 and 5. Per region, this would reduce the number of commit messages for a full dataset update from around 450 to around 20-30.

Since nearly all of the Quintel generated datasets will probably use the same 20-30 commit messages, it may be even better still, if technically possible, if these messages only have to be stored once. In this way, the total number of commit messages in the database would be 20-30 (+ some custom messages), rather than 20-30 _per dataset_. (The same holds for input field values by the way, e.g. most likely we will want to set the whole industry sector to 0 for all neighbourhoods).

Ideally, it should be _possible_ to set individual commit messages per region and per value in the csv, but also to use one message for multiple values/regions, with as little database entries as necessary. The latter is more important.

We discussed whether we should be able to generate datasets by running one script with one csv file or whether we should create one csv file per commit (i.e. one csv file per unique commit message). I strongly prefer the former: with 20-30 unique commit messages it would be very cumbersome if we have to generate 30 csv's.

_Actions:_
- Investigate possibilities for reducing the number of commits/commit messages/database entries

Supersedes: https://github.com/quintel/etlocal/issues/120

### PR DESCRIPTION
**Pull request by antw**
@michieldenhaan This is the new CSV importer for ETLocal as described in https://github.com/quintel/etlocal/issues/128#issuecomment-402487924. There are quite a lot of tests included, but if you already have CSV/YAML for a future update I'd be more than happy to test with those prior to merging.

The CSV should have a `geo_id` field to identify each dataset but no longer needs an `area`. As discussed, it only updates existing datasets and will not create new ones if the `geo_id` isn't already in the database.

---

Run `bundle exec rails generate data_migration <name>` to create a new data migration. This will create a DB migration and associated data.csv and commits.yml files. The data and commits will be imported into the Quintel datasets.

CSVs should specify the datasets to be edited, and the new values, while commits.yml associates individual attributes with commit messages. Multiple attributes may be grouped together in one commit.

For example:

    data.csv
    --------

    geo_id,number_of_residences,number_of_inhabitants,number_of_cars
    BU16800000,1000,3000,850
    BU16800100,2000,5000,2800

    commits.yml
    -----------

    ---
    - fields:
      - number_of_residences
      - number_of_inhabitants
      message:
        Update number of residences and inhabitants based on new data
        sourced from ...

    - fields:
      - number_of_cars
      message:
        Assign new number of cars based on data from ...

Also supported is an `:all` attribute which may be used when creating a single commit. This will cause the commit to use all the fields in the CSV:

    - fields:
      - :all
      message:
        ...

Closes #128

### CODE REVIEW

**Comment by antw** [comment]
I should also add that lacking a CSV/YAML for a "real" update, I haven't been able to test the real-world performance of the new importer. My guess is that it will be worse than the old one: while fewer commits will be created, the new importer checks that the value in the CSV is different from the one in the database [to avoid creating unnecessary DatasetEdit records](https://github.com/quintel/etlocal/issues/120#issuecomment-400285945).

If the performance is problematic, I'll take a second look at it.

**Comment by michieldenhaan** [comment]
Works perfectly! It's really useful that the importer checks whether the values in the CSV are different from the database. Performance is good as well I think: 35 seconds for about 100 datasets, 180 keys, 7 commits on my not-so-powerful laptop. I guess that means that we can update all 380 municipalities within a few minutes time. 

Import:
1 rails server -p 3000 fsevent_watch 2018-08-22 14-57-02

Result:
etlocal httplocalhost3000 2018-08-22 15-03-37

And export to ETSource:
energy transition model - your free independent comprehensive fact-based scenario builder httpetmodel test 2018-08-22 15-21-01

**Comment by michieldenhaan** [comment]
@antw Can I merge this?
I made one minor change to align the output of the import script to the input of the export script 🤓  (``rake etsource:export`` takes ``DATASET=id1,id2,id3..`` so the importer now returns ``id1,id2,id3..`` rather than ``id1 id2 id3..``).
Are you okay with this? (See https://github.com/quintel/etlocal/pull/135/commits/091b256e89e9c2114c0411a042bd62360114c4a1, you can squash it into your commit if you like)

**Comment by antw** [comment]
> @antw Can I merge this?

Sure, go ahead!

**Pull request merged**
