### PR TITLE
Dataset importer

### PR DESCRIPTION
**Pull request by antw**
This is the new dataset importer, used to populate a new database. It expects the same format as [the CSV importer](https://github.com/quintel/etlocal/pull/135):

* A **data.csv** file containing the `geo_id`, area `name`, and a list of dataset attributes to be imported.
* A **commits.yml** file mapping the dataset attributes to commits which should be created.

These files should be placed in **db/seeds** prior to running `bundle exec rails db:setup` on a new copy of ETLocal. [A short README](https://github.com/quintel/etlocal/blob/dataset-importer/db/seeds/README.md) explains the format of the two files in more detail.

Like the old version, re-running the importer will destroy all old commits and dataset edits for the "robot"-owned (Quintel) datasets specified in the CSV file. Datasets owned by other users are unaffected.

@michieldenhaan When you have time, it would be useful if you could test this out and see if it meets your expectations. There are differences from the old nl_datasets.csv format:

1. The area name is specified with a `name` attribute instead of `area`.

   I opted for `name` over `geo_name` as it should play a little nicer with Rails data validations. If you have a strong preference for `geo_name`, please let me know and it can be changed.

2. The old dataset importer had separate columns for the province, municipality, etc:

   | type | province_code | municipality_code | district_code | neighborhood_code | area_name |
   | ---- | ------------- | ----------------- | ------------- | ----------------- | --------- |
   | BU | 22 | 1680 | 0 | 0 | Annen | ... |
   | BU | 22 | 1680 | 1 | 0 | Eext | ... |

   From this data, it would construct the `geo_id`, zero-padding the codes as necessary (a municipality code of "16" would become "0016", a district code of "0" becomes "00", etc). By contrast, the new dataset importer expects to be provided a valid `geo_id`:

   | geo_id | name | ... |
   | ------ | ---- | --- |
   | BU16800000 | Annen | ... |
   | BU16800100 | Eext | ... |

   Therefore, the responsibility for creating the valid `geo_id` is on whatever tool is used to create the CSV. If this is a problem, and you want to revert back to using separate columns for each code, let me know.

### CODE REVIEW

**Comment by antw** [comment]
> The importer fails when a dataset name contains accented characters (see screenshot below). Is it possible to allow those characters?

Likely the text encoding of the CSV being imported is not UTF-8. If you open the CSV file in your text editor there should be a "text encoding" or "save with encoding" option somewhere. Many text editors will show you the current encoding somewhere near the bottom of the window, for example in VS Code:

screen shot 2018-10-02 at 16 09 07

You might see "latin1", "ISO 8859-1", or perhaps something else. Once saved in UTF-8, the text editor will reflect the change and it should be possible to import the file:

screen shot 2018-10-02 at 16 11 31

> The importer doesn't recognise the has_industry and has_agriculture attributes.

The old importer didn't touch these attributes either, and in my own tests they don't appear to have any effect on the datasets when exported to ETSource. These attributes likely should be supported, but I think that's a different issue to this pull request.

> The importer count starts at 0 instead of 1

The CSV *should* end with a blank line, but it's not mandatory. I've pushed a commit which will provide a correct count for CSVs without the blank line.

**Comment by michieldenhaan** [comment]
Thanks! Another question: in the future we may want to add some custom regions to ETLocal (e.g. a region that is the sum of multiple municipalities). Can this be done by simply creating a new data.csv containing _only_ the new custom regions and running ``bundle exec rails db:setup``?

**Comment by antw** [comment]
>  Can this be done by simply creating a new data.csv containing only the new custom regions and running bundle exec rails db:setup?

We'd probably do that with a migration. `db:setup` is intended for setting up new databases: it's not something that should be run in production more than once.

Currently migrations only allow you to update datasets, but it would be a one-line change to allow it to create them.

**Comment by antw** [comment]
> Currently migrations only allow you to update datasets, but it would be a one-line change to allow it to create them.

I've added support for this. It is disabled by default, but future data migrations will explain how to turn it on: https://github.com/quintel/etlocal/blob/d5a5cdd16a285746a39168174df3dda396f9d89e/lib/generators/data_migration/templates/migration.rb#L8-L16

**Comment by michieldenhaan** [comment]
Really awesome work!

**Pull request merged**
